#!/bin/sh
mkdir -p dist
NODE_ENV=production node_modules/.bin/browserify lib/index.js -t reactify -t browserify-shim -t envify --detect-globals false -s ReactScrollbars > dist/react-scrollbars.js
node_modules/.bin/uglifyjs dist/react-scrollbars.js --compress warnings=false > dist/react-scrollbars.min.js
echo "gzipped, the global build is:"
echo "`gzip -c dist/react-scrollbars.min.js | wc -c` bytes"